name: Build ğŸ› ï¸ Test ğŸ§ª Deploy ğŸš€

on:
  push:
    branches:
      - main
  schedule:
    - cron: "5 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./src
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v2
      - name: ğŸ¦„ Use .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x"
      - name: âœ¨ NuGet Restore
        run: dotnet restore
        working-directory: ${{env.working-directory}}
      - name: ğŸ› ï¸ Build Solution
        run: dotnet build --configuration Release --no-restore
        working-directory: ${{env.working-directory}}
      - name: ğŸ§ª Run Tests
        run: dotnet test --no-restore --verbosity normal
        working-directory: ${{env.working-directory}}
      - name: ğŸš€ Deploy Website
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az storage blob upload-batch --destination $web --source ./sample/content --connection-string "<BLOB_CONNECTION_STRING>"
